### PR TITLE
[IE]Add the op Min and its node.js binding

### PR DESCRIPTION
**Pull request by lionkunonly**
Only implement the Op Min based on Openvino. Here is the screenshot for the node.js tesets:
image

This PR should have conflicts with the PR for Op Max.

### CODE REVIEW

**Comment by huningxin** [comment]
@lionkunonly , please help fix the conflicts. Thanks!

**Comment by lionkunonly** [comment]
> @lionkunonly , please help fix the conflicts. Thanks!

Fixed.

**Review by fujunwei — APPROVED** [review]
LGTM.

**Comment by fujunwei** [comment]
Merge it, thanks.

**Pull request merged**
