### PR TITLE
[IE] add Op Pow and its node.js binding

### PR DESCRIPTION
**Pull request by lionkunonly**
The implementation based on IE for Op pow and its Node.js binding. The screenshots for Node.js tests is here:
image

### CODE REVIEW

**Comment by huningxin** [comment]
@lionkunonly , please help fix the conflicts. Thanks.

**Review by fujunwei — APPROVED** [review]
LGTM.

**Comment by huningxin** [comment]
Ping @lionkunonly to fix the conflicts. Thanks.

**Comment by lionkunonly** [comment]
> Ping @lionkunonly to fix the conflicts. Thanks.

The conflicts are fixed.

**Review by huningxin — APPROVED** [review]
LGTM, thanks @lionkunonly !

**Pull request merged**
