### PR TITLE
Add CI to auto roll DEPS.

### PR DESCRIPTION
**Pull request by BruceDai**

### CODE REVIEW

**Comment by bbernhar** [comment]
@BruceDai LGTM. But ensure "branch protection rules" are required on this repo. In settings, add a new rule for "main" branch that corresponds to the CI workflow that should run before completing the roll.

**Comment by BruceDai** [comment]
> But ensure "branch protection rules" are required on this repo. In settings, add a new rule for "main" branch that corresponds to the CI workflow that should run before completing the roll.

@bbernhar Thanks for your kind reminder.
 
Since I'm not the owner of this webnn-native repository, I don't have the permission to configure settings and don't know which settings of this webnn-native repository like. 
Here, I take following branche settings of my own repository for example, I checked these settings, but I couldn't find an explicit or relevant rule of running CI workflow before completing the roll. 


image

Could you please guide us how to configure this rule, thanks a lot.

**Comment by bbernhar** [comment]
@BruceDai Sure. Add the branch-name (eg. `main`) to "Branch name pattern" field then _edit_ this entry. Ensure "Require status checks to pass before merging" is select and enter the workflow-job names to the "Status checks that are required." list. The job names correspond to the `job:` field in the workflow file. That's all. =)

**Comment by BruceDai** [comment]
@fujunwei Please help merge this PR firstly, let's see the status whether this CI works.  If not, I would involve @anssiko to help set `branch protection rules` for `main` branch, thanks.

**Comment by fujunwei** [comment]
Merge it.

**Pull request merged**
