### PR TITLE
Add CI for DML backend

### PR DESCRIPTION
**Pull request by mingmingtasd**

### CODE REVIEW

**Comment by mingmingtasd** [comment]
Will failed to build for main branch because main branch has removed files such as BackendDML.cpp under dml. So I suggest adding these CI after merging https://github.com/webmachinelearning/webnn-native/pull/287. WDYT? @BruceDai @fujunwei

**Comment by fujunwei** [comment]
Could you please check in the instance.cpp first, so that the main branch can pass the CI?

**Comment by mingmingtasd** [comment]
> Could you please check in the instance.cpp first, so that the main branch can pass the CI?

Do you mean merge the change in instance firstly? @fujunwei

**Comment by mingmingtasd** [comment]
PTAL, thanks! @fujunwei @BruceDai 
The failure seems caused by  getting baseline for regression check, since there is no real implementation to support test cases, the failure should be expected, right? If so, can we merge it? Then I think the next PR will succeed to run CI?

**Comment by fujunwei** [comment]
> PTAL, thanks! @fujunwei @BruceDai The failure seems caused by getting baseline for regression check, since there is no real implementation to support test cases, the failure should be expected, right? If so, can we merge it? Then I think the next PR will succeed to run CI?

There are errors when running the end-to-end tests, please disable it if it's hard to fix:
```
[==========] Running 359 tests from 40 test suites.
[----------] Global test environment set-up.
unknown file: error: SEH exception with code 0xc0000005 thrown in auxiliary test code (environments or event listeners).
```

**Comment by mingmingtasd** [comment]
> > PTAL, thanks! @fujunwei @BruceDai The failure seems caused by getting baseline for regression check, since there is no real implementation to support test cases, the failure should be expected, right? If so, can we merge it? Then I think the next PR will succeed to run CI?
> 
> There are errors when running the end-to-end tests, please disable it if it's hard to fix:
> 
> ```
> [==========] Running 359 tests from 40 test suites.
> [----------] Global test environment set-up.
> unknown file: error: SEH exception with code 0xc0000005 thrown in auxiliary test code (environments or event listeners).
> ```
OK, I have disable end2end tests for dml backend. @fujunwei

**Comment by mingmingtasd** [comment]
Close this PR since DML backend implementation has been removed.

**Pull request closed without merging**
