### PR TITLE
Add style transfer example

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@fujunwei, the sample failed with following error:

```shell
> style_transfer@0.0.1 start /home/wm/work/webml/webnn/webnn-native/node/examples/electron/style_transfer
> electron-forge start --

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
Copy WebNN libs and samples successfully!
✔ Launching Application
Uncaptured Error type is 1, message is Argument scale is not a 1D tensor.
    at Validate (../../src/webnn_native/ops/InstanceNorm.cpp:56)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
    at Validate (../../src/webnn_native/Operator.cpp:60)
Uncaptured Error type is 1, message is Argument inputs are invalid.
```

Error from invoking following JS code, PTAL, thanks!

```js
      return this.builder_.instanceNormalization(conv2D,
          {scale: this.builder_.squeeze(variableMul), bias: this.builder_.squeeze(variableAdd)});
```

**Comment by fujunwei** [comment]
It's fixing in https://github.com/webmachinelearning/webnn-native/pull/140, could you please file a issue to track the example launch slowly.

**Review by fujunwei — APPROVED** [review]
LGTM.

**Comment by Honry** [comment]
Thanks @fujunwei, I've created issue https://github.com/otcshare/webnn-native/issues/812.

**Comment by fujunwei** [comment]
Merge it, thanks.

**Pull request merged**
