### PR TITLE
Add a new DirectML backend 

### PR DESCRIPTION
**Pull request by mingmingtasd**

### CODE REVIEW

**Comment by huningxin** [comment]
@mingmingtasd , what's our transition plan? Should we maintain two implementations for a while. We probably need to keep the current DirectMLX based implementation and add the DirectML.h based implementation side-by-side.

Thoughts? @fujunwei

**Comment by fujunwei** [comment]
> @mingmingtasd , what's our transition plan? Should we maintain two implementations for a while. We probably need to keep the current DirectMLX based implementation and add the DirectML.h based implementation side-by-side.
> 
> Thoughts? @fujunwei

Sounds good.

**Comment by mingmingtasd** [comment]
> @mingmingtasd , what's our transition plan? Should we maintain two implementations for a while. We probably need to keep the current DirectMLX based implementation and add the DirectML.h based implementation side-by-side.
> 
> Thoughts? @fujunwei

I agree we'd better keep the DirectMLX based implementation, because I will continue optimizing my code, just hold it here. @fujunwei @huningxin

**Comment by mingmingtasd** [comment]
As we plan to build this implementation without DirectMLX.h and device.cpp as a new backend, which backend name is appropriate? Do you have any suggestions? @huningxin @fujunwei

**Comment by fujunwei** [comment]
> As we plan to build this implementation without DirectMLX.h and device.cpp as a new backend, which backend name is appropriate? Do you have any suggestions? @huningxin @fujunwei

How about add a suffix named `graph` at end of usage that means the backend implemenation use dml graph API directly, for example webnn_enable_dml to webnn_enable_dml_graph

**Comment by mingmingtasd** [comment]
I have rebased the PR, added the new dml backend, there is no regression. PTAL again, thanks! @fujunwei

**Comment by fujunwei** [comment]
> I have rebased the PR, added the new dml backend, there is no regression. PTAL again, thanks! @fujunwei

Do you mean all tests can run as directMLX backend?  could you please add CI for the backend including node.js and native?

**Comment by mingmingtasd** [comment]
> > I have rebased the PR, added the new dml backend, there is no regression. PTAL again, thanks! @fujunwei
> 
> Do you mean all tests can run as directMLX backend? could you please add CI for the backend including node.js and native?

Yes, all end2end cases of supported ops can pass as DirectMLX backend. ConvTranspose2d and Gru will be added by @miaobin  after the PR merged.
As discussed with @BruceDai , he will add the CI in another PR, right? @BruceDai

**Comment by fujunwei** [comment]
Merge it.

**Comment by fujunwei** [comment]
Revert it because endtoend tests failed, @mingmingtasd please fix it, thanks.

.\out\dml\webnn_end2end_tests.exe
[==========] Running 357 tests from 39 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from AddTests
[ RUN      ] AddTests.AddConstantAndInput
Error: Failed to do DMLCreateDevice(mD3D12Device.Get(), dmlCreateDeviceFlags, IID_PPV_ARGS(&mDevice))
GPGMM Error (tid:17152): Assertion failure at ../../src/webnn/native/dml/GraphDML.cpp:539 (Graph): 0

**Comment by fujunwei** [comment]
@BruceDai @mingmingtasd  please add the CI in the PR, so we can make sure most tests and samples can work, thanks.

**Pull request merged**
