### PR TITLE
Enable PIX Capture for debug builds.

### PR DESCRIPTION
**Pull request by bbernhar**
Allows PIX to capture the DML backend for analysis.

### CODE REVIEW

**Comment by bbernhar** [comment]
@fujunwei PTAL!

@mingmingtasd FYI, this is how to enable PIX.

**Review by fujunwei — APPROVED** [review]
Merge it, thanks

**Comment by mingmingtasd** [comment]
> @fujunwei PTAL!
> 
> @mingmingtasd FYI, this is how to enable PIX.

Thanks, got it. What is the PIX Capture? Could you help introduce the feature of it? @bbernhar

**Comment by bbernhar** [comment]
@mingmingtasd 

PIX is a tool that records API calls made to DX which can be played back with additional instrumentation (timing). No need to modify code. A PIX capture analysis eliminates the CPU bottleneck so you can keep the GPU busy enough to get meaningful profiling data.

**Pull request merged**
