### PR TITLE
Support Gru on DML backend

### PR DESCRIPTION
**Pull request by miaobin**
When the code runs to `CreateOperatorNode` on DML backend It will be crashed. 
@mingmingtasd @fujunwei Could you help me find where is the problem? Thanks a lot!

### CODE REVIEW

**Comment by mingmingtasd** [comment]
> When the code runs to `CreateOperatorNode` on DML backend It will be crashed.
> @mingmingtasd @fujunwei Could you help me find where is the problem? Thanks a lot!

I suggest to write a dml native case for Gru, please refer to this [commit](https://github.com/mingmingtasd/DirectML/commit/9c7fc10623c918a17f9b524b214e3a52d5e060d1). @miaobin

**Comment by miaobin** [comment]
I have wrote a DML native case for Gru:
```
import pydirectml as dml
import numpy as np

steps = 2
batchSize = 3
inputSize = 3
hiddenSize = 5
numDirections = 1

input_bindings = []

def append_input_tensor(builder: dml.GraphBuilder, input_bindings: list, input_tensor: dml.TensorDesc):
    tensor = dml.input_tensor(builder, len(input_bindings), input_tensor)
    input_bindings.append(dml.Binding(tensor, np.zeros(tensor.get_output_desc().sizes)))
    return tensor

# Create a GPU device, and build a model graph.
device = dml.Device(True, True)
builder = dml.GraphBuilder(device)
data_type = dml.TensorDataType.FLOAT32
flags = dml.TensorFlags.OWNED_BY_DML

input_data = [1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
input_array = np.array(input_data, np.float32)
input = dml.input_tensor(builder, 0, dml.TensorDesc(data_type, [1, steps, batchSize, inputSize]))
input_bindings.append(dml.Binding(input, input_array))
weight = append_input_tensor(builder, input_bindings, dml.TensorDesc(data_type, flags, [1, numDirections, 3 * hiddenSize, inputSize]))
recurrentWeight = append_input_tensor(builder, input_bindings, dml.TensorDesc(data_type, flags, [1, numDirections, 3 * hiddenSize, hiddenSize]))

gru = dml.gru(
  input = input,
  weight = weight,
  recurrence = recurrentWeight,
  activation_descs = [dml.FusedActivation(dml.OperatorType.ACTIVATION_SIGMOID), dml.FusedActivation(dml.OperatorType.ACTIVATION_SIGMOID)],
  direction = dml.RecurrentNetworkDirection.FORWARD,
  output_options = dml.OutputOptions.Single
)

# Compile the expression graph into a compiled operator
op = builder.build(dml.ExecutionFlags.NONE, [gru])

# Compute the result
output_data = device.compute(op, input_bindings, [gru])
output_tensor = np.array(output_data[0], np.float32)

print(output_tensor)
```
And got the similar error with webnn-native (could not create operator):
```
RuntimeError: m_device->CreateOperator(&opDesc, IID_PPV_ARGS(&op))
```
Reported an [issue](https://github.com/microsoft/DirectML/issues/153) to DirectML.

**Comment by fujunwei** [comment]
onnxruntime\core\providers\dml\DmlExecutionProvider\src\Operators\DmlOperatorRecurrentNeuralNetwork.cpp is onnx runtime implemenation, you can also investigate it.

**Comment by miaobin** [comment]
@fujunwei After opening the Debug Layer tool we found the cause of the error and optimized the code. PTAL, thanks!

**Comment by miaobin** [comment]
The original creation method will miss some optional inputs, and cause a mismatch between the input and the edge when creating the graph. And we have send a [PR ](https://github.com/microsoft/DirectML/pull/210)to DML upstream to fix the issue. @fujunwei PTAL, thanks!

**Review by fujunwei — APPROVED** [review]
LGTM.

**Comment by fujunwei** [comment]
Merge it, thanks.

**Pull request merged**
