### PR TITLE
[Node] add Op Slice and fix a error in Op Squeeze

### PR DESCRIPTION
**Pull request by lionkunonly**
Add the Op Slice to the Node.js. And fix a error in Op Squeeze. The `slice`-related test cases are passed.

### CODE REVIEW

**Review by fujunwei — APPROVED** [review]
LGTM, i will merge it when the cl is green.

**Comment by lionkunonly** [comment]
> LGTM, i will merge it when the cl is green.

I do not understand the root of the cl error. Do you have any idea?

**Comment by fujunwei** [comment]
@lionkunonly please update the commit to trigger the CI again, thanks.

**Comment by lionkunonly** [comment]
@fujunwei I have updated the commit. But this PR can not pass the checks all.

>FileNotFoundError: [Errno 2] No such file or directory: 'D:\\a\\webnn-native\\webnn-native\\..\\baseline_end2endtests.json'
It is the error report of the failed check. But there is not a file called `baseline_end2endtests.json` in `webnn_native`

**Comment by fujunwei** [comment]
@BruceDai could you please double check the CI workable?

**Comment by BruceDai** [comment]
@lionkunonly This CI failure is of running baseline exception, please retrigger CI by summitting empty commit using following command:
```sh
git commit --allow-empty - m "retrigger ci"
git push origin kunliang/AddSliceNode
```

**Comment by lionkunonly** [comment]
@fujunwei  All checks are green

**Comment by fujunwei** [comment]
Merge it, thanks.

**Pull request merged**
