### PR TITLE
Revert "Add check memory leak for windows"

### PR DESCRIPTION
**Pull request by fujunwei**
Reverts webmachinelearning/webnn-native#201 because new PR will be failed.

@BruceDai @wangli69087 Could you please check the memory leak size to detect regression not the key words "memory leaks", i think we should enable the CI until fixing all memory leaks if we can't check memory leak size.

@huningxin WDYT?

### CODE REVIEW

**Comment by huningxin** [comment]
> @huningxin WDYT?

I agree with @fujunwei . If there is a memory leak, please file an issue and fix that before we enable the CI for that.

**Review by huningxin — APPROVED** [review]
LGTM

**Comment by huningxin** [comment]
> If there is a memory leak, please file an issue and fix that before we enable the CI for that.

@BruceDai , does the plan sounds good to you?

**Comment by BruceDai** [comment]
> @BruceDai , does the plan sound good to you?

Yes, I'm OK to revert this CI, thanks.

**Comment by BruceDai** [comment]
There's already an issue https://github.com/otcshare/webnn-native/issues/874 for memory leak to track.

**Comment by huningxin** [comment]
Thanks @BruceDai .

https://github.com/webmachinelearning/webnn-native/pull/238 seems to fix that issue. As it has been merged, I'll re-run the bot before I revert the check in CI.

**Comment by huningxin** [comment]
Re-run memory leak check CI of https://github.com/webmachinelearning/webnn-native/pull/239 still failed. I'll merge this PR to unblock other PRs.

**Pull request merged**
