### PR TITLE
Fix depot_tools installation steps for Windows

### PR DESCRIPTION
**Pull request by huningxin**
Developers need to set DEPOT_TOOLS_WIN_TOOLCHAIN=0

### CODE REVIEW

**Comment by huningxin** [comment]
@wchao1115, PTAL. Thanks.

**Comment by huningxin** [comment]
@fujunwei , Please also take a look. Thanks!

**Review by fujunwei — APPROVED** [review]
LGTM.

**Comment by wchao1115** [comment]
Looks good. Thanks for fixing it.

**Pull request merged**
