### PR TITLE
Add CI for testing WebNN XNNPACK backend on both Windows and Linux platforms

### PR DESCRIPTION
**Pull request by BruceDai**
@fujunwei PTAL, thanks.

### CODE REVIEW

**Comment by BruceDai** [comment]
@fujunwei I'm checking CI failures with latest code, please hold on.

**Comment by BruceDai** [comment]
CI failures 
`ninja: error: '../../src/webnn/native/xnnpack/BackendXNN.cpp', needed by 'obj/src/webnn/native/sources/BackendXNN.obj'` 
is due to lack of xnnpack/BackendXNN.cpp and xnnpack/BackendXNN.h files


On #254 
image

@lisa0314 PTAL, thanks

**Comment by lisa0314** [comment]
@BruceDai Sorry for make this error due to my patch. I have pushed a new [PR](https://github.com/webmachinelearning/webnn-native/pull/262) to fix it. Thanks!

**Comment by BruceDai** [comment]
Thanks @lisa0314. 
Now CI for XNNPACK backend can pass, @fujunwei PTAL, thanks.

**Comment by fujunwei** [comment]
Get it, merging.

**Pull request merged**
