### PR TITLE
Update README.md by removing DML information from CI status table

### PR DESCRIPTION
**Pull request by mingmingtasd**
PTAL, thanks! @BruceDai @fujunwei

### CODE REVIEW

**Comment by fujunwei** [comment]
Why do not you add the CI for the dml backend?

**Comment by mingmingtasd** [comment]
Close it, will add the CI files.

**Comment by mingmingtasd** [comment]
Reopen this PR to delete CI information for DML backend. @fujunwei @BruceDai

**Comment by fujunwei** [comment]
Merge it, thanks.

**Pull request merged**
