### PR TITLE
Add ninja in DEPS

### LINKED ISSUE #393: Ninja failed: Could not find Ninja in the third_party of the current project, nor in your PATH.
image

DEPS may need to be updated.

### PR DESCRIPTION
**Pull request by mingmingtasd**
Fix #393. Update DEPS to align with chromium's DEPS, otherwise, ninja will fail. PTAL, thanks! @fujunwei @huningxin

### CODE REVIEW

**Comment by BruceDai** [comment]
Thanks @mingmingtasd to fix this issue.
These CI failures are due to fail build **main** branch to get baseline for regression check with the same fixing issue. 
@fujunwei I suggest merge it directly.

**Comment by fujunwei** [comment]
I can't merge it because the button of "Merge pull request" is disabled on my side.

**Comment by anssiko** [comment]
I had a discussion with @BruceDai about this PR. I'll merge this without waiting for all the checks to be successful.

**Comment by BruceDai** [comment]
Thanks @anssiko to help merge it.
I will investigate configurations for fixing such case.

**Comment by mingmingtasd** [comment]
Thanks! @anssiko @BruceDai @fujunwei

**Pull request merged**
