### PR TITLE
Add CI for OpenVINO backend on Windows platform.

### PR DESCRIPTION
**Pull request by BruceDai**
Please have a preview on the [link](https://github.com/BruceDai/webnn-native/runs/3377624236?check_suite_focus=true).
This new badge is OpenVINO backend (Windows).

### CODE REVIEW

**Comment by BruceDai** [comment]
Depend on #95.

@huningxin PTAL, thanks.

**Comment by BruceDai** [comment]
The next PR of CI for Node Binding with WebNN native by OpenVINO backend on Windows platform will submit after this PR merged.

**Comment by huningxin** [comment]
@BruceDai , could you please look at the failure of the OpenVINO backend (Windows)?

**Comment by BruceDai** [comment]
Hi @huningxin, the failure was due to #95 script unmerged. Should I re-trigger CI with an empty commit?   Thanks.

**Comment by BruceDai** [comment]
@huningxin  I retriggered the CI, please wait a while to see the CI status, thanks.

**Comment by BruceDai** [comment]
All checks PASS by rerunning CI. @huningxin Please take another look, thanks.

**Review by huningxin — APPROVED** [review]

**Pull request merged**
