### PR TITLE
Remove tracked thirdparty/gpgmm in github

### PR DESCRIPTION
**Pull request by fujunwei**

### CODE REVIEW

**Comment by Honry** [comment]
>[1:30:00] fatal: write error: No space left on device
[1:30:00] fatal: fetch-pack: invalid index-pack output

Looks like there's no enough space left on the CI device.

**Comment by fujunwei** [comment]
@huningxin CI can work now, the commit remove tracked thirdparty/gpgmm in github PTAL, thanks.
cc @mingmingtasd @miaobin

**Review by huningxin — APPROVED** [review]
LGTM, thanks @fujunwei !

**Comment by mingmingtasd** [comment]
> @huningxin CI can work now, the commit remove tracked thirdparty/gpgmm in github PTAL, thanks.

Thanks! And it will also fix issue #183 ,right? @fujunwei

**Comment by fujunwei** [comment]
> > @huningxin CI can work now, the commit remove tracked thirdparty/gpgmm in github PTAL, thanks.
> 
> Thanks! And it will also fix issue #183 ,right? @fujunwei

Yes, i will close it after merging the commit.

**Comment by fujunwei** [comment]
Merge it, thanks for reviewing.

**Pull request merged**
