### PR TITLE
[IE] Add Op Max and bind it to the Node.js

### PR DESCRIPTION
**Pull request by lionkunonly**
[IE] Add the Op Max and its node binding. However, the implementation based DML is not completed.

### CODE REVIEW

**Comment by huningxin** [comment]
@lionkunonly , please fix the conflicts and if it is ready for review, please request @fujunwei or me to review. If you won't plan to implement the DirectML backend in this PR, please file an issue to track that gap. Thanks.

**Comment by lionkunonly** [comment]
> @lionkunonly , please fix the conflicts and if it is ready for review, please request @fujunwei or me to review. If you won't plan to implement the DirectML backend in this PR, please file an issue to track that gap. Thanks.

I'd like to solve the DIrectML backend in this PR. But I do not the API of the DIrectML backend for Op Max. Cloud you give me some suggestions? @mingmingtasd

**Comment by huningxin** [comment]
@lionkunonly , please help solve the conflicts after #44 merged. Thanks!

**Comment by lionkunonly** [comment]
> @lionkunonly , please help solve the conflicts after #44 merged. Thanks!

I have rebased this PR. Here is the screenshot for the node.js binding for Op Max

Screenshot from 2021-08-11 12-59-05

**Review by fujunwei — APPROVED** [review]
LGTM.

**Pull request merged**
