### PR TITLE
Fix the typo issue in readme

### PR DESCRIPTION
**Pull request by mingmingtasd**
PTAL, thanks! @BruceDai @fujunwei

### CODE REVIEW

**Review by huningxin — APPROVED** [review]
LGTM, thanks @mingmingtasd !

**Comment by fujunwei** [comment]
@mingmingtasd please trigger CI again with updating the commit

**Comment by mingmingtasd** [comment]
fix #213 , done. @fujunwei

**Comment by fujunwei** [comment]
Merge it, thanks.

**Pull request merged**
